<?php
namespace Generic\Controller;

// require 'Store/Model/Customer.php';
// require 'Store/Model/Product.php';

//use Generic\Model\Greeting;

defined('is_running') or die('Not an entry point...');


class Greeting
{
	protected	$greetingObject = NULL;

	// main constructor of Object
    public function __construct()
    {
//		message("Generic\Controller\Greeting::__construct()");

		$this->Init();
	}

	protected function Init()
	{
//		message("Generic\Controller\Greeting::Init()");

//		$this->greetingObject = new Greeting();
	}

	public function Show()
	{
//		message("Generic\Controller\Greeting::Show()");
		echo "Show…<br />";
		echo $br.$br.$greetinx.$br.$br."<i>Generated by Generic Controller</i><hr>";

//		echo $this->greetingObject->GetMessage();
	}
}
